/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  RemoteStreamHandle,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AgentTeamAddMemberRequest, AgentTeamAddMemberResult, AgentTeamArchiveChannelRequest, AgentTeamArchiveChannelResult, AgentTeamArchiveMemberRequest, AgentTeamArchiveMemberResult, AgentTeamChangesRequest, AgentTeamChangesResult, AgentTeamClearMemberContextRequest, AgentTeamClearMemberContextResult, AgentTeamClientMemberStatus, AgentTeamCreateChannelRequest, AgentTeamCreateChannelResult, AgentTeamGetAttachmentRequest, AgentTeamGetAttachmentResult, AgentTeamGetHumanAvatarRequest, AgentTeamGetHumanAvatarResult, AgentTeamHumanProfileRequest, AgentTeamHumanProfileResult, AgentTeamInbox, AgentTeamInboxRequest, AgentTeamJoinChannelRequest, AgentTeamJoinChannelResult, AgentTeamJoinWorkspaceRequest, AgentTeamJoinWorkspaceResult, AgentTeamLeaveWorkspaceRequest, AgentTeamLeaveWorkspaceResult, AgentTeamMemberResult, AgentTeamMembersRequest, AgentTeamPromoteThreadRequest, AgentTeamPromoteThreadResult, AgentTeamPutAttachmentRequest, AgentTeamPutAttachmentResult, AgentTeamPutHumanAvatarRequest, AgentTeamPutHumanAvatarResult, AgentTeamRecoverMemberRequest, AgentTeamRecoverMemberResult, AgentTeamRemoveChannelMemberRequest, AgentTeamRemoveChannelMemberResult, AgentTeamRemoveHumanAvatarRequest, AgentTeamRemoveHumanAvatarResult, AgentTeamReplyRequest, AgentTeamReplyResult, AgentTeamResolveTaskRefsRequest, AgentTeamResolveTaskRefsResult, AgentTeamResolveThreadRefsRequest, AgentTeamResolveThreadRefsResult, AgentTeamSendMessageRequest, AgentTeamSendMessageResult, AgentTeamSetHumanProfileRequest, AgentTeamSetHumanProfileResult, AgentTeamTaskRequest, AgentTeamTaskResult, AgentTeamThreadAttentionRequest, AgentTeamThreadAttentionResult, AgentTeamThreadHistory, AgentTeamThreadHistoryRequest, AgentTeamThreadObservations, AgentTeamThreadObservationsRequest, AgentTeamThreadReadRequest, AgentTeamThreadReadResult, AgentTeamUpdateChannelRequest, AgentTeamUpdateChannelResult, AgentTeamUpdateMemberRequest, AgentTeamView, AgentTeamViewRequest } from 'dsh-sophia-entities/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6167656e745465616d {
    addMember: (request: AgentTeamAddMemberRequest) => Promise<RemoteResult<AgentTeamAddMemberResult>>
    archiveChannel: (request: AgentTeamArchiveChannelRequest) => Promise<RemoteResult<AgentTeamArchiveChannelResult>>
    archiveMember: (request: AgentTeamArchiveMemberRequest) => Promise<RemoteResult<AgentTeamArchiveMemberResult>>
    changeAttention: (request: AgentTeamThreadAttentionRequest) => Promise<RemoteResult<AgentTeamThreadAttentionResult>>
    changes: (request: AgentTeamChangesRequest, signal?: AbortSignal) => RemoteStreamHandle<AgentTeamChangesResult, never>
    changeTask: (request: AgentTeamTaskRequest) => Promise<RemoteResult<AgentTeamTaskResult>>
    clearMemberContext: (request: AgentTeamClearMemberContextRequest) => Promise<RemoteResult<AgentTeamClearMemberContextResult>>
    createChannel: (request: AgentTeamCreateChannelRequest) => Promise<RemoteResult<AgentTeamCreateChannelResult>>
    getAttachment: (request: AgentTeamGetAttachmentRequest) => Promise<RemoteResult<AgentTeamGetAttachmentResult>>
    getHumanAvatar: (request: AgentTeamGetHumanAvatarRequest) => Promise<RemoteResult<AgentTeamGetHumanAvatarResult>>
    humanProfile: (_request: AgentTeamHumanProfileRequest) => Promise<RemoteResult<AgentTeamHumanProfileResult>>
    inbox: (request: AgentTeamInboxRequest) => Promise<RemoteResult<AgentTeamInbox>>
    joinChannel: (request: AgentTeamJoinChannelRequest) => Promise<RemoteResult<AgentTeamJoinChannelResult>>
    joinWorkspace: (request: AgentTeamJoinWorkspaceRequest) => Promise<RemoteResult<AgentTeamJoinWorkspaceResult>>
    leaveWorkspace: (request: AgentTeamLeaveWorkspaceRequest) => Promise<RemoteResult<AgentTeamLeaveWorkspaceResult>>
    members: (request: AgentTeamMembersRequest) => Promise<RemoteResult<readonly AgentTeamClientMemberStatus[]>>
    promoteThread: (request: AgentTeamPromoteThreadRequest) => Promise<RemoteResult<AgentTeamPromoteThreadResult>>
    putAttachment: (request: AgentTeamPutAttachmentRequest) => Promise<RemoteResult<AgentTeamPutAttachmentResult>>
    putHumanAvatar: (request: AgentTeamPutHumanAvatarRequest) => Promise<RemoteResult<AgentTeamPutHumanAvatarResult>>
    readThread: (request: AgentTeamThreadReadRequest) => Promise<RemoteResult<AgentTeamThreadReadResult>>
    recoverMember: (request: AgentTeamRecoverMemberRequest) => Promise<RemoteResult<AgentTeamRecoverMemberResult>>
    removeChannelMember: (request: AgentTeamRemoveChannelMemberRequest) => Promise<RemoteResult<AgentTeamRemoveChannelMemberResult>>
    removeHumanAvatar: (request: AgentTeamRemoveHumanAvatarRequest) => Promise<RemoteResult<AgentTeamRemoveHumanAvatarResult>>
    reply: (request: AgentTeamReplyRequest) => Promise<RemoteResult<AgentTeamReplyResult>>
    resolveTaskRefs: (request: AgentTeamResolveTaskRefsRequest) => Promise<RemoteResult<AgentTeamResolveTaskRefsResult>>
    resolveThreadRefs: (request: AgentTeamResolveThreadRefsRequest) => Promise<RemoteResult<AgentTeamResolveThreadRefsResult>>
    sendMessage: (request: AgentTeamSendMessageRequest) => Promise<RemoteResult<AgentTeamSendMessageResult>>
    setHumanProfile: (request: AgentTeamSetHumanProfileRequest) => Promise<RemoteResult<AgentTeamSetHumanProfileResult>>
    threadHistory: (request: AgentTeamThreadHistoryRequest) => Promise<RemoteResult<AgentTeamThreadHistory>>
    threadObservations: (request: AgentTeamThreadObservationsRequest) => Promise<RemoteResult<AgentTeamThreadObservations>>
    updateChannel: (request: AgentTeamUpdateChannelRequest) => Promise<RemoteResult<AgentTeamUpdateChannelResult>>
    updateMember: (request: AgentTeamUpdateMemberRequest) => Promise<RemoteResult<AgentTeamMemberResult>>
    view: (request: AgentTeamViewRequest) => Promise<RemoteResult<AgentTeamView>>
  }
  interface TypertRemoteMap {
    'agentTeam/addMember': (request: AgentTeamAddMemberRequest) => Promise<RemoteResult<AgentTeamAddMemberResult>>
    'agentTeam/archiveChannel': (request: AgentTeamArchiveChannelRequest) => Promise<RemoteResult<AgentTeamArchiveChannelResult>>
    'agentTeam/archiveMember': (request: AgentTeamArchiveMemberRequest) => Promise<RemoteResult<AgentTeamArchiveMemberResult>>
    'agentTeam/changeAttention': (request: AgentTeamThreadAttentionRequest) => Promise<RemoteResult<AgentTeamThreadAttentionResult>>
    'agentTeam/changes': (request: AgentTeamChangesRequest, signal?: AbortSignal) => RemoteStreamHandle<AgentTeamChangesResult, never>
    'agentTeam/changeTask': (request: AgentTeamTaskRequest) => Promise<RemoteResult<AgentTeamTaskResult>>
    'agentTeam/clearMemberContext': (request: AgentTeamClearMemberContextRequest) => Promise<RemoteResult<AgentTeamClearMemberContextResult>>
    'agentTeam/createChannel': (request: AgentTeamCreateChannelRequest) => Promise<RemoteResult<AgentTeamCreateChannelResult>>
    'agentTeam/getAttachment': (request: AgentTeamGetAttachmentRequest) => Promise<RemoteResult<AgentTeamGetAttachmentResult>>
    'agentTeam/getHumanAvatar': (request: AgentTeamGetHumanAvatarRequest) => Promise<RemoteResult<AgentTeamGetHumanAvatarResult>>
    'agentTeam/humanProfile': (_request: AgentTeamHumanProfileRequest) => Promise<RemoteResult<AgentTeamHumanProfileResult>>
    'agentTeam/inbox': (request: AgentTeamInboxRequest) => Promise<RemoteResult<AgentTeamInbox>>
    'agentTeam/joinChannel': (request: AgentTeamJoinChannelRequest) => Promise<RemoteResult<AgentTeamJoinChannelResult>>
    'agentTeam/joinWorkspace': (request: AgentTeamJoinWorkspaceRequest) => Promise<RemoteResult<AgentTeamJoinWorkspaceResult>>
    'agentTeam/leaveWorkspace': (request: AgentTeamLeaveWorkspaceRequest) => Promise<RemoteResult<AgentTeamLeaveWorkspaceResult>>
    'agentTeam/members': (request: AgentTeamMembersRequest) => Promise<RemoteResult<readonly AgentTeamClientMemberStatus[]>>
    'agentTeam/promoteThread': (request: AgentTeamPromoteThreadRequest) => Promise<RemoteResult<AgentTeamPromoteThreadResult>>
    'agentTeam/putAttachment': (request: AgentTeamPutAttachmentRequest) => Promise<RemoteResult<AgentTeamPutAttachmentResult>>
    'agentTeam/putHumanAvatar': (request: AgentTeamPutHumanAvatarRequest) => Promise<RemoteResult<AgentTeamPutHumanAvatarResult>>
    'agentTeam/readThread': (request: AgentTeamThreadReadRequest) => Promise<RemoteResult<AgentTeamThreadReadResult>>
    'agentTeam/recoverMember': (request: AgentTeamRecoverMemberRequest) => Promise<RemoteResult<AgentTeamRecoverMemberResult>>
    'agentTeam/removeChannelMember': (request: AgentTeamRemoveChannelMemberRequest) => Promise<RemoteResult<AgentTeamRemoveChannelMemberResult>>
    'agentTeam/removeHumanAvatar': (request: AgentTeamRemoveHumanAvatarRequest) => Promise<RemoteResult<AgentTeamRemoveHumanAvatarResult>>
    'agentTeam/reply': (request: AgentTeamReplyRequest) => Promise<RemoteResult<AgentTeamReplyResult>>
    'agentTeam/resolveTaskRefs': (request: AgentTeamResolveTaskRefsRequest) => Promise<RemoteResult<AgentTeamResolveTaskRefsResult>>
    'agentTeam/resolveThreadRefs': (request: AgentTeamResolveThreadRefsRequest) => Promise<RemoteResult<AgentTeamResolveThreadRefsResult>>
    'agentTeam/sendMessage': (request: AgentTeamSendMessageRequest) => Promise<RemoteResult<AgentTeamSendMessageResult>>
    'agentTeam/setHumanProfile': (request: AgentTeamSetHumanProfileRequest) => Promise<RemoteResult<AgentTeamSetHumanProfileResult>>
    'agentTeam/threadHistory': (request: AgentTeamThreadHistoryRequest) => Promise<RemoteResult<AgentTeamThreadHistory>>
    'agentTeam/threadObservations': (request: AgentTeamThreadObservationsRequest) => Promise<RemoteResult<AgentTeamThreadObservations>>
    'agentTeam/updateChannel': (request: AgentTeamUpdateChannelRequest) => Promise<RemoteResult<AgentTeamUpdateChannelResult>>
    'agentTeam/updateMember': (request: AgentTeamUpdateMemberRequest) => Promise<RemoteResult<AgentTeamMemberResult>>
    'agentTeam/view': (request: AgentTeamViewRequest) => Promise<RemoteResult<AgentTeamView>>
  }
  interface TypertRemoteNamespaceMap {
    'agentTeam': TypertRemoteNamespace$6167656e745465616d
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
